sudo: required
services:
        - docker

before_install:
        - docker build -t tombenjaminmorris/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run tombenjaminmorris/react-test npm test -- --coverage

after_success:
        - docker build -t tombenjaminmorris/multi-client ./client
        - docker build -t tombenjaminmorris/multi-nginx ./nginx
        - docker build -t tombenjaminmorris/multi-server ./server
        - docker build -t tombenjaminmorris/multi-worker ./worker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push tombenjaminmorris/multi-client
        - docker push tombenjaminmorris/multi-nginx
        - docker push tombenjaminmorris/multi-server
        - docker push tombenjaminmorris/multi-worker

deploy:
        provider: elasticbeanstalk
        region: eu-west-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-eu-west-2-905016994436
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY